//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeminarskiRad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predbiljezba
    {
        public int IdPredbiljezba { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Adresa { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> IdSeminar { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Seminar Seminar { get; set; }
    }
}
