//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeminarskiRad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeminarskiRadEntities : DbContext
    {
        public SeminarskiRadEntities()
            : base("name=SeminarskiRadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Predbiljezba> Predbiljezba { get; set; }
        public virtual DbSet<Seminar> Seminar { get; set; }
        public virtual DbSet<Zaposlenik> Zaposlenik { get; set; }
    }
}
